publish_period: 0.02
dxl_read_period: 0.02
dxl_write_period: 0.02

# set if use_cmd_vel is true
mobile_robot_config:                
  seperation_between_wheels_x: 0.1775
  seperation_between_wheels_y: 0.18
  radius_of_wheel: 0.0333333333333