kani_joint_state_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
kani_steering_controller:
  # type: "four_wheel_steering_controller/FourWheelSteeringController"
  # front_wheel: ["leftFront_wheel_joint", "rightFront_wheel_joint"]
  # rear_wheel: ["leftBack_wheel_joint", "rightBack_wheel_joint"]
  # front_steering: ["leftFront_steer_joint", "rightFront_steer_joint"]
  # rear_steering: ["leftBack_steer_joint", "rightBack_steer_joint"]
  # publish_rate: 50
  # pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  # twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  # cmd_vel_timeout: 25.0 # not tested here

  # # Base frame_id
  # base_frame_id: base_footprint

  # # Odometry fused with IMU is published by robot_localization, so
  # # no need to publish a TF based on encoders alone.
  # enable_odom_tf: true
  # enable_twist_cmd: true

  # # Wheel separation and diameter. These are both optional.
  # # diff_drive_controller will attempt to read either one or both from the
  # # URDF if not specified as a parameter
  # track : 0.1775 # left_right separation
  # wheel_base : 0.18 # front_rear separation
  # wheel_radius : 0.0333333333333 #0.10

  # ==================================


  type: "four_wheel_steering_controller/FourWheelSteeringController"
  front_wheel: ["leftFront_wheel_joint", "rightFront_wheel_joint"]
  rear_wheel: ["leftBack_wheel_joint", "rightBack_wheel_joint"]
  front_steering: ["leftFront_steer_joint", "rightFront_steer_joint"]
  rear_steering: ["leftBack_steer_joint", "rightBack_steer_joint"]
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 25.0 # not tested here


  # Base frame_id
  base_frame_id: base_footprint

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true
  enable_twist_cmd: true

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  track : 0.1775 # left_right separation
  wheel_base : 0.18 # front_rear separation
  wheel_radius : 0.0333333333333 #0.10
