<?xml version="1.0"?>

<robot name="sensor_a1" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:include filename="$(find kani_description)/urdf/sensors/rplidar_A1.gazebo.xacro" />
  
  <xacro:macro name="sensor_a1" params="name parent *origin">
    <xacro:property name="laser_sensor_radius" value="0.03514"/>
    <xacro:property name="stepper_radius" value="0.016"/>
    <xacro:property name="origin_to_sensor_centre_z_offset" value="0.042"/>
    <xacro:property name="origin_to_sensor_centre_y_offset" value="${0.09674-laser_sensor_radius-stepper_radius}"/>

    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="laser_link" />
    </joint>

    <link name="${name}_link">
      <visual>
      <origin xyz=" -0.00714 0.00714 0" rpy="0 0 ${-pi/2}"/>
      <!-- -0.00714 0.00714 0 -->
        <geometry>
          <mesh filename="package://kani_description/meshes/rplidar.stl"/>
        </geometry>
        <material name="Red" />
      </visual>
      <collision>
        <origin xyz="-0.00714 0.00714 0" rpy="0 0 ${-pi/2}"/>
        <geometry>
          <mesh filename="package://kani_description/meshes/rplidar.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.000001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
      </inertial>
    </link>

    <!-- extensions -->
    <xacro:rplidar_laser name="${name}" ros_topic="/scan" update_rate="5.5" ray_count="360" min_angle="${-pi}" max_angle="${pi}"/>

  </xacro:macro>




</robot>
